Fix invalid shell syntax in docs-merge-pipeline
PingCAP-QE/devops-config pull request #145
Opened 2022-10-13 17:06 UTC by Oreoxmt

Ref: https://stackoverflow.com/a/18558871

Jenkins uses POSIX shell instead of bash when running scripts. `[[ $TARGET_BRANCH == release-* ]]` is invalid.

2022-10-13 17:10 UTC, Oreoxmt commented
cc @shczhen @purelind

2022-10-13 23:37 UTC, purelind requested changes
Testing in sh, there is still a failure

2022-10-14 02:59 UTC, purelind commented
> Testing in sh, there is still a failure

test this with sh on local, it passed, will merge this later.

2022-10-14 02:59 UTC, merged

2022-10-14 03:02 UTC, shczhen commented
We can use `echo $TARGET_BRANCH | cut -c1-8` if not work.